# Reference: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
dist: focal
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
  - "3.9"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib numpy scikit-learn scipy
  - conda activate test-environment

  - conda install -c conda-forge scikit-optimize
  - pip install tensorflow tensorflow-probability
  - conda install pytorch cpuonly -c pytorch
  - pip install jax flax optax

script:
  # Your test script goes here
  - DDEBACKEND=tensorflow.compat.v1 python -c "import deepxde"
  - DDEBACKEND=tensorflow python -c "import deepxde"
  - DDEBACKEND=pytorch python -c "import deepxde"
  - DDEBACKEND=jax python -c "import deepxde"
