# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Clone

on:
  pull_request:
    branches: [ "master" ]

  pull_request_target:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Clone:
    # Don't run on forked repos.
    if: github.repository_owner == 'PaddlePaddle'
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: master
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1000


    - name: Download bos client
      env:
        WORK: "/home/runner/work/community"
      if: steps.cache_bos_client.outputs.cache-hit != 'true'
      run: |
        cd $WORK
        wget -q --no-proxy -O bos_upload.py  https://paddle-docker-tar.cdn.bcebos.com/bos_upload.py --no-check-certificate
    - name: Push paddle-action.tar.gz to bos
      env:
        WORK: "/home/runner/work/community"
        AK: ${{ secrets.AK }}
        SK: ${{ secrets.SK }}
      run: |
        cd $WORK
        tar -zcf Paddle-action.tar.gz community
        python -m pip install bce-python-sdk==0.8.74
        python bos_upload.py Paddle-action.tar.gz xly-devops/PR/Paddle/${PR_ID}/${COMMIT_ID}
